### PR TITLE
Use git & x-checker-data

### PR DESCRIPTION
**Pull request by Doomsdayrs**
For ease of upgrading later.
Also moves the file to a non version specific format.

### CODE REVIEW

**Comment by orowith2os** [comment]
I don't think the shared-modules repo is checked by flathub for updates, and not having the file versioned could be a bit weird later on for other manifests. Is this really a good idea to have?

**Comment by orowith2os** [comment]
Also, an archive was used to reduce the burden on builders. Using an archive takes up less resources than cloning a git repo.

**Comment by Doomsdayrs** [comment]
> I don't think the shared-modules repo is checked by flathub for updates, and not having the file versioned could be a bit weird later on for other manifests. Is this really a good idea to have?

How could it be weird, there are manifests that are not versioned?

**Comment by Doomsdayrs** [comment]
> Also, an archive was used to reduce the burden on builders. Using an archive takes up less resources than cloning a git repo.

Ah, nevermind the PR then

**Comment by orowith2os** [comment]
They aren't versioned *yet*; I'd rather have them be versioned so that, if multiple modules are used, it won't mess with packages using these modules, like, say, if SDL 2.26.2 were to break some features in 2.26.1, but apps couldn't stop that due to not being able to define a specific version that's compatible with other modules.

**Pull request closed without merging**
